//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenTicket.Resources.Views.Clients {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddTicket {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddTicket() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GoldenTicket.Resources.Views.Clients.AddTicket", typeof(AddTicket).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Add_Ticket {
            get {
                return ResourceManager.GetString("Add Ticket", resourceCulture);
            }
        }
        
        internal static string Abroad {
            get {
                return ResourceManager.GetString("Abroad", resourceCulture);
            }
        }
        
        internal static string Contact_Person_on_Site {
            get {
                return ResourceManager.GetString("Contact Person on Site", resourceCulture);
            }
        }
        
        internal static string Destination_Address {
            get {
                return ResourceManager.GetString("Destination Address", resourceCulture);
            }
        }
        
        internal static string Destination_Country {
            get {
                return ResourceManager.GetString("Destination Country", resourceCulture);
            }
        }
        
        internal static string Destination_Instituition {
            get {
                return ResourceManager.GetString("Destination Instituition", resourceCulture);
            }
        }
        
        internal static string End_Date_and_Time {
            get {
                return ResourceManager.GetString("End Date and Time", resourceCulture);
            }
        }
        
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        internal static string Reason_of_Travel {
            get {
                return ResourceManager.GetString("Reason of Travel", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Sources_of_Funding {
            get {
                return ResourceManager.GetString("Sources of Funding", resourceCulture);
            }
        }
        
        internal static string Start_Date_and_Time {
            get {
                return ResourceManager.GetString("Start Date and Time", resourceCulture);
            }
        }
        
        internal static string Transportation {
            get {
                return ResourceManager.GetString("Transportation", resourceCulture);
            }
        }
        
        internal static string Urgent {
            get {
                return ResourceManager.GetString("Urgent", resourceCulture);
            }
        }
    }
}
